# Generated by Django 4.1.7 on 2023-05-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=500)),
                ("phone", models.IntegerField(max_length=15)),
                ("message", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="posts",
            name="slug",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
